/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmarCitaIdRouteImport } from './routes/confirmar-cita.$id'
import { Route as AgendarSlugRouteImport } from './routes/agendar.$slug'
import { Route as AppRecetasRouteImport } from './routes/_app.recetas'
import { Route as AppPacientesRouteImport } from './routes/_app.pacientes'
import { Route as AppInventarioRouteImport } from './routes/_app.inventario'
import { Route as AppHistorialRouteImport } from './routes/_app.historial'
import { Route as AppEstadisticasRouteImport } from './routes/_app.estadisticas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsentimientoRouteImport } from './routes/_app.consentimiento'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'
import { Route as AppComportamientoRouteImport } from './routes/_app.comportamiento'
import { Route as AppBrandingRouteImport } from './routes/_app.branding'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppAdministracionRouteImport } from './routes/_app.administracion'
import { Route as AppRecetasNuevaRouteImport } from './routes/_app.recetas.nueva'
import { Route as AppPacientesIdRouteImport } from './routes/_app.pacientes.$id'
import { Route as AppPacientesIdHojaRouteImport } from './routes/_app.pacientes.$id.hoja'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarCitaIdRoute = ConfirmarCitaIdRouteImport.update({
  id: '/confirmar-cita/$id',
  path: '/confirmar-cita/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSlugRoute = AgendarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgendarRoute,
} as any)
const AppRecetasRoute = AppRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppEstadisticasRoute = AppEstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentimientoRoute = AppConsentimientoRouteImport.update({
  id: '/consentimiento',
  path: '/consentimiento',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppComportamientoRoute = AppComportamientoRouteImport.update({
  id: '/comportamiento',
  path: '/comportamiento',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandingRoute = AppBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministracionRoute = AppAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => AppRoute,
} as any)
const AppRecetasNuevaRoute = AppRecetasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppRecetasRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPacientesRoute,
} as any)
const AppPacientesIdHojaRoute = AppPacientesIdHojaRouteImport.update({
  id: '/hoja',
  path: '/hoja',
  getParentRoute: () => AppPacientesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/login': typeof LoginRoute
  '/administracion': typeof AppAdministracionRoute
  '/agenda': typeof AppAgendaRoute
  '/branding': typeof AppBrandingRoute
  '/comportamiento': typeof AppComportamientoRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/consentimiento': typeof AppConsentimientoRoute
  '/dashboard': typeof AppDashboardRoute
  '/estadisticas': typeof AppEstadisticasRoute
  '/historial': typeof AppHistorialRoute
  '/inventario': typeof AppInventarioRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/recetas': typeof AppRecetasRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/confirmar-cita/$id': typeof ConfirmarCitaIdRoute
  '/pacientes/$id': typeof AppPacientesIdRouteWithChildren
  '/recetas/nueva': typeof AppRecetasNuevaRoute
  '/pacientes/$id/hoja': typeof AppPacientesIdHojaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/login': typeof LoginRoute
  '/administracion': typeof AppAdministracionRoute
  '/agenda': typeof AppAgendaRoute
  '/branding': typeof AppBrandingRoute
  '/comportamiento': typeof AppComportamientoRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/consentimiento': typeof AppConsentimientoRoute
  '/dashboard': typeof AppDashboardRoute
  '/estadisticas': typeof AppEstadisticasRoute
  '/historial': typeof AppHistorialRoute
  '/inventario': typeof AppInventarioRoute
  '/pacientes': typeof AppPacientesRouteWithChildren
  '/recetas': typeof AppRecetasRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/confirmar-cita/$id': typeof ConfirmarCitaIdRoute
  '/pacientes/$id': typeof AppPacientesIdRouteWithChildren
  '/recetas/nueva': typeof AppRecetasNuevaRoute
  '/pacientes/$id/hoja': typeof AppPacientesIdHojaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/agendar': typeof AgendarRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/administracion': typeof AppAdministracionRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/branding': typeof AppBrandingRoute
  '/_app/comportamiento': typeof AppComportamientoRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/consentimiento': typeof AppConsentimientoRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estadisticas': typeof AppEstadisticasRoute
  '/_app/historial': typeof AppHistorialRoute
  '/_app/inventario': typeof AppInventarioRoute
  '/_app/pacientes': typeof AppPacientesRouteWithChildren
  '/_app/recetas': typeof AppRecetasRouteWithChildren
  '/agendar/$slug': typeof AgendarSlugRoute
  '/confirmar-cita/$id': typeof ConfirmarCitaIdRoute
  '/_app/pacientes/$id': typeof AppPacientesIdRouteWithChildren
  '/_app/recetas/nueva': typeof AppRecetasNuevaRoute
  '/_app/pacientes/$id/hoja': typeof AppPacientesIdHojaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/login'
    | '/administracion'
    | '/agenda'
    | '/branding'
    | '/comportamiento'
    | '/configuracion'
    | '/consentimiento'
    | '/dashboard'
    | '/estadisticas'
    | '/historial'
    | '/inventario'
    | '/pacientes'
    | '/recetas'
    | '/agendar/$slug'
    | '/confirmar-cita/$id'
    | '/pacientes/$id'
    | '/recetas/nueva'
    | '/pacientes/$id/hoja'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/login'
    | '/administracion'
    | '/agenda'
    | '/branding'
    | '/comportamiento'
    | '/configuracion'
    | '/consentimiento'
    | '/dashboard'
    | '/estadisticas'
    | '/historial'
    | '/inventario'
    | '/pacientes'
    | '/recetas'
    | '/agendar/$slug'
    | '/confirmar-cita/$id'
    | '/pacientes/$id'
    | '/recetas/nueva'
    | '/pacientes/$id/hoja'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/agendar'
    | '/login'
    | '/_app/administracion'
    | '/_app/agenda'
    | '/_app/branding'
    | '/_app/comportamiento'
    | '/_app/configuracion'
    | '/_app/consentimiento'
    | '/_app/dashboard'
    | '/_app/estadisticas'
    | '/_app/historial'
    | '/_app/inventario'
    | '/_app/pacientes'
    | '/_app/recetas'
    | '/agendar/$slug'
    | '/confirmar-cita/$id'
    | '/_app/pacientes/$id'
    | '/_app/recetas/nueva'
    | '/_app/pacientes/$id/hoja'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AgendarRoute: typeof AgendarRouteWithChildren
  LoginRoute: typeof LoginRoute
  ConfirmarCitaIdRoute: typeof ConfirmarCitaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-cita/$id': {
      id: '/confirmar-cita/$id'
      path: '/confirmar-cita/$id'
      fullPath: '/confirmar-cita/$id'
      preLoaderRoute: typeof ConfirmarCitaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$slug': {
      id: '/agendar/$slug'
      path: '/$slug'
      fullPath: '/agendar/$slug'
      preLoaderRoute: typeof AgendarSlugRouteImport
      parentRoute: typeof AgendarRoute
    }
    '/_app/recetas': {
      id: '/_app/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof AppRecetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes': {
      id: '/_app/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historial': {
      id: '/_app/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estadisticas': {
      id: '/_app/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof AppEstadisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consentimiento': {
      id: '/_app/consentimiento'
      path: '/consentimiento'
      fullPath: '/consentimiento'
      preLoaderRoute: typeof AppConsentimientoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comportamiento': {
      id: '/_app/comportamiento'
      path: '/comportamiento'
      fullPath: '/comportamiento'
      preLoaderRoute: typeof AppComportamientoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branding': {
      id: '/_app/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AppBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administracion': {
      id: '/_app/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AppAdministracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recetas/nueva': {
      id: '/_app/recetas/nueva'
      path: '/nueva'
      fullPath: '/recetas/nueva'
      preLoaderRoute: typeof AppRecetasNuevaRouteImport
      parentRoute: typeof AppRecetasRoute
    }
    '/_app/pacientes/$id': {
      id: '/_app/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppPacientesRoute
    }
    '/_app/pacientes/$id/hoja': {
      id: '/_app/pacientes/$id/hoja'
      path: '/hoja'
      fullPath: '/pacientes/$id/hoja'
      preLoaderRoute: typeof AppPacientesIdHojaRouteImport
      parentRoute: typeof AppPacientesIdRoute
    }
  }
}

interface AppPacientesIdRouteChildren {
  AppPacientesIdHojaRoute: typeof AppPacientesIdHojaRoute
}

const AppPacientesIdRouteChildren: AppPacientesIdRouteChildren = {
  AppPacientesIdHojaRoute: AppPacientesIdHojaRoute,
}

const AppPacientesIdRouteWithChildren = AppPacientesIdRoute._addFileChildren(
  AppPacientesIdRouteChildren,
)

interface AppPacientesRouteChildren {
  AppPacientesIdRoute: typeof AppPacientesIdRouteWithChildren
}

const AppPacientesRouteChildren: AppPacientesRouteChildren = {
  AppPacientesIdRoute: AppPacientesIdRouteWithChildren,
}

const AppPacientesRouteWithChildren = AppPacientesRoute._addFileChildren(
  AppPacientesRouteChildren,
)

interface AppRecetasRouteChildren {
  AppRecetasNuevaRoute: typeof AppRecetasNuevaRoute
}

const AppRecetasRouteChildren: AppRecetasRouteChildren = {
  AppRecetasNuevaRoute: AppRecetasNuevaRoute,
}

const AppRecetasRouteWithChildren = AppRecetasRoute._addFileChildren(
  AppRecetasRouteChildren,
)

interface AppRouteChildren {
  AppAdministracionRoute: typeof AppAdministracionRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppBrandingRoute: typeof AppBrandingRoute
  AppComportamientoRoute: typeof AppComportamientoRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppConsentimientoRoute: typeof AppConsentimientoRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstadisticasRoute: typeof AppEstadisticasRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppPacientesRoute: typeof AppPacientesRouteWithChildren
  AppRecetasRoute: typeof AppRecetasRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministracionRoute: AppAdministracionRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppBrandingRoute: AppBrandingRoute,
  AppComportamientoRoute: AppComportamientoRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppConsentimientoRoute: AppConsentimientoRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstadisticasRoute: AppEstadisticasRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppPacientesRoute: AppPacientesRouteWithChildren,
  AppRecetasRoute: AppRecetasRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AgendarRouteChildren {
  AgendarSlugRoute: typeof AgendarSlugRoute
}

const AgendarRouteChildren: AgendarRouteChildren = {
  AgendarSlugRoute: AgendarSlugRoute,
}

const AgendarRouteWithChildren =
  AgendarRoute._addFileChildren(AgendarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AgendarRoute: AgendarRouteWithChildren,
  LoginRoute: LoginRoute,
  ConfirmarCitaIdRoute: ConfirmarCitaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
